### ISSUE TITLE
Question about C aux  Classifier

### ISSUE THREAD

**Issue by mikaizhu** [raven38/OSSGAN#1]
I'm a little confused about your algorithm, how did you use C to differentiate between open-set and close-set data?

![image](https://user-images.githubusercontent.com/59464933/177460781-cffed469-f371-4774-84e8-2f85253d1cc3.png)

**Comment by raven38** [comment]
Thanks for your question.
In the algorithm, we don't explicitly differentiate between open-set and close-set data.
The discriminator implictly differentiates betweem them using their entropy.

**Comment by mikaizhu** [comment]
> Thanks for your question. In the algorithm, we don't explicitly differentiate between open-set and close-set data. The discriminator implictly differentiates betweem them using their entropy.

thanks for your reply, I have some questions?
1. how you train the classifier C？and what is the structure of classifier C?
2. can i use Minist dataset in with your data? if it is possible, what should i do ?

**Comment by raven38** [comment]
1. The classifier shares a feature extractor with a discriminator, and the head consists of one fully-connected layer. We update the parameters of the classifier at the same time as the discriminator update.
2. To integrate additional unlabeled data into the dataset, we can extend the HDF5 file of the dataset. In an HDF5 file, the lablels of unlabeled data is -1.
